### ISSUE TITLE
(Name, phonenumber) dataset from Enron

### ISSUE THREAD

**Issue by krishnakanthnakkav2** [hanyins/LM_Association_Quantification#1]
Hello Authors,

Can you please clarify if you have released the (name, phonenumber) Enron dataset in this repo? If not, can you please suggest where I can download it?

Thanks

**Comment by krishnakanthnakkav2** [comment]
Dear Authors,

I will be grateful if you could provide pointers to extract the name and phone number pairs from the enron email dataset. Thank you.

**Comment by jeffhj** [comment]
Sorry for just finding this issue on github. We have sent the dataset to you via email :)

**Comment by liyihan19** [comment]
> Dear Authors, 
> I will be grateful if you could provide pointers to extract the name and phone number pairs from the enron email dataset. Thank you.

I am wondering if it would be possible for you to share the PII associated pairs involved in the LAMA and Enron datasets. If that's not feasible, could you please provide me with a guide on how to extract these associated pairs? It would be of great help to my studies.
Thank you so much for your consideration.
